-- ============================================================
--   CLASS_DOCUMENTS TABLE & RLS POLICIES
--   Run this script in your Supabase SQL Editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.class_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  title TEXT NOT NULL,
  document_type TEXT NOT NULL DEFAULT 'md', -- 'md' or 'pdf'
  content TEXT, -- For markdown documents
  link TEXT, -- For PDF links or external URLs
  submitted_by TEXT DEFAULT 'Anonymous'
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.class_documents ENABLE ROW LEVEL SECURITY;

-- 1. SELECT: Anyone can view class documents
CREATE POLICY "class_documents: select policy"
  ON public.class_documents FOR SELECT
  TO anon, authenticated
  USING (true);

-- 2. INSERT: Only officers and moderators can add class documents
CREATE POLICY "class_documents: insert policy"
  ON public.class_documents FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  );

-- 3. UPDATE: Only officers and moderators can update class documents
CREATE POLICY "class_documents: update policy"
  ON public.class_documents FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  );

-- 4. DELETE: Only officers and moderators can delete class documents
CREATE POLICY "class_documents: delete policy"
  ON public.class_documents FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  );
