-- ============================================================
--   STUDY_MATERIALS TABLE & RLS POLICIES
--   Run this script in your Supabase SQL Editor.
--   Note: This script uses inline subqueries to check for officer
--   and moderator whitelists to ensure it runs successfully
--   even on a clean database setup.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.study_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  link TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Quiz', -- 'Quiz', 'Exam', 'Lecture', 'Other'
  study_type TEXT NOT NULL DEFAULT 'lesson', -- 'lesson', 'week', 'task'
  course_id BIGINT REFERENCES public.courses(id) ON DELETE SET NULL,
  week_number INTEGER,
  lesson_name TEXT,
  task_name TEXT,
  submitted_by TEXT DEFAULT 'Anonymous',
  approved BOOLEAN DEFAULT FALSE NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.study_materials ENABLE ROW LEVEL SECURITY;

-- 1. SELECT: Anyone (anonymous or authenticated) can view approved materials.
--    Only officers and moderators can view pending (unapproved) materials.
CREATE POLICY "study_materials: select policy"
  ON public.study_materials FOR SELECT
  TO anon, authenticated
  USING (
    approved = true 
    OR (
      auth.role() = 'authenticated' 
      AND (
        EXISTS (
          SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
        )
        OR EXISTS (
          SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
        )
      )
    )
  );

-- 2. INSERT: Anyone can submit new materials (both anon and authenticated).
--    Submissions default to approved = false (unapproved) for moderator review.
CREATE POLICY "study_materials: insert policy"
  ON public.study_materials FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    approved = false
  );

-- 3. UPDATE: Only officers and moderators can update entries (e.g., approve them or edit details).
CREATE POLICY "study_materials: update policy"
  ON public.study_materials FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  );

-- 4. DELETE: Only officers and moderators can delete/reject reviewer links.
CREATE POLICY "study_materials: delete policy"
  ON public.study_materials FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  );
