import type { SegmentedLayer } from '@/types/editor';

/**
 * Default SAM2-cutout photo layers for the Plaza map (stored in `public/maps/plaza/layers/`).
 * Scaled precisely to match the 2200x1500 world map dimensions (scaled down from original 3730x2215 cutout canvas).
 */
export const DEFAULT_PLAZA_LAYERS: SegmentedLayer[] = [
  {
    id: 'layer_random-pole',
    name: 'random pole',
    url: '/maps/plaza/layers/random-pole.png',
    x: 931,
    y: 1414,
    w: 336,
    h: 86,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_msi9932t_1640',
    name: 'fountain',
    url: '/maps/plaza/layers/fountain-2.png',
    x: 1004,
    y: 659,
    w: 192,
    h: 205,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_msi9d3td_2055',
    name: 'schoolhouse',
    url: '/maps/plaza/layers/schoolhouse.png',
    x: 922,
    y: 19,
    w: 321,
    h: 325,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
    crop: { x: 0, y: 0, w: 321, h: 226 },
  },
  {
    id: 'layer_msi9i4ro_9828',
    name: 'fence',
    url: '/maps/plaza/layers/fence.png',
    x: 880,
    y: 78,
    w: 440,
    h: 264,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_msi9k0pm_7659',
    name: 'marketplace',
    url: '/maps/plaza/layers/marketplace.png',
    x: 305,
    y: 256,
    w: 296,
    h: 180,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_msi9mg78_7319',
    name: 'board',
    url: '/maps/plaza/layers/board.png',
    x: 1626,
    y: 308,
    w: 270,
    h: 136,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_msi9ncki_1106',
    name: 'bigtree',
    url: '/maps/plaza/layers/bigtree.png',
    x: 1872,
    y: 425,
    w: 316,
    h: 330,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
    crop: { x: 0, y: 0, w: 316, h: 237 },
  },
  {
    id: 'layer_msi9o5pz_3125',
    name: 'bigrock',
    url: '/maps/plaza/layers/bigrock.png',
    x: 1830,
    y: 1055,
    w: 179,
    h: 166,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_msi9p8mj_1386',
    name: 'rocky',
    url: '/maps/plaza/layers/rocky.png',
    x: 620,
    y: 129,
    w: 160,
    h: 90,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_msi9q335_8120',
    name: 'bush1',
    url: '/maps/plaza/layers/bush1.png',
    x: 1508,
    y: 179,
    w: 90,
    h: 72,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_msi9qpa7_1315',
    name: 'bush2',
    url: '/maps/plaza/layers/bush2.png',
    x: 1617,
    y: 150,
    w: 75,
    h: 63,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_msi9ri8t_4320',
    name: 'rocky2',
    url: '/maps/plaza/layers/rocky2.png',
    x: 724,
    y: 1183,
    w: 185,
    h: 135,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
    crop: { x: 0, y: 0, w: 185, h: 83 },
  },
  {
    id: 'layer_msi9s3s5_3458',
    name: 'Object 13',
    url: '/maps/plaza/layers/object-13.png',
    x: 1273,
    y: 1089,
    w: 141,
    h: 122,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
    crop: { x: 0, y: 0, w: 141, h: 84 },
  },
  {
    id: 'layer_msibb5qt_9544',
    name: 'banderitas',
    url: '/maps/plaza/layers/banderitas.png',
    x: 405,
    y: 558,
    w: 1062,
    h: 689,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
    crop: { x: 326, y: 0, w: 736, h: 238 },
  },
];
