import type { SegmentedLayer } from '@/types/editor';

/**
 * Default SAM2-cutout photo layers for the Plaza map (stored in `public/maps/plaza/layers/`).
 * These default photo layers ensure that photo cutouts (bigtree, fountain, marketplace, board, etc.)
 * render with accurate 2.5D Y-sorting draw order even when no custom editor draft exists.
 */
export const DEFAULT_PLAZA_LAYERS: SegmentedLayer[] = [
  {
    id: 'layer_banderitas',
    name: 'Banderitas Overhead',
    url: '/maps/plaza/layers/banderitas.png',
    x: 0,
    y: 0,
    w: 2200,
    h: 1500,
    slot: 'character',
    zOffset: 5000,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_bigtree',
    name: 'Big Tree',
    url: '/maps/plaza/layers/bigtree.png',
    x: 1630,
    y: 150,
    w: 569,
    h: 665,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_fountain',
    name: 'Plaza Fountain',
    url: '/maps/plaza/layers/fountain.png',
    x: 920,
    y: 590,
    w: 360,
    h: 422,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_marketplace',
    name: 'Marketplace Stalls',
    url: '/maps/plaza/layers/marketplace.png',
    x: 200,
    y: 120,
    w: 553,
    h: 406,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_board',
    name: 'Bulletin Board',
    url: '/maps/plaza/layers/board.png',
    x: 1510,
    y: 240,
    w: 503,
    h: 277,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_bushes',
    name: 'Plaza Bushes',
    url: '/maps/plaza/layers/bushes.png',
    x: 1500,
    y: 330,
    w: 342,
    h: 205,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_rocky',
    name: 'Rocky Formation',
    url: '/maps/plaza/layers/rocky.png',
    x: 1150,
    y: 1020,
    w: 301,
    h: 225,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_random_pole',
    name: 'Lamppost & Poles',
    url: '/maps/plaza/layers/random-pole.png',
    x: 700,
    y: 600,
    w: 625,
    h: 168,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_object_7',
    name: 'Plaza Decor',
    url: '/maps/plaza/layers/object-7.png',
    x: 1750,
    y: 950,
    w: 332,
    h: 337,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
];
