import type { SegmentedLayer } from '@/types/editor';

/**
 * Default SAM2-cutout photo layers for the Plaza map (stored in `public/maps/plaza/layers/`).
 * Scaled precisely to match the 2200x1500 world map dimensions (scaled down from original 3730x2215 cutout canvas).
 */
export const DEFAULT_PLAZA_LAYERS: SegmentedLayer[] = [
  {
    id: 'layer_banderitas',
    name: 'Banderitas Overhead',
    url: '/maps/plaza/layers/banderitas.png',
    x: 0,
    y: 0,
    w: 2200,
    h: 1500,
    slot: 'character',
    zOffset: 5000,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_bigtree',
    name: 'Big Tree',
    url: '/maps/plaza/layers/bigtree.png',
    x: 1630,
    y: 220,
    w: 336,
    h: 450,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_fountain',
    name: 'Plaza Fountain',
    url: '/maps/plaza/layers/fountain.png',
    x: 906,
    y: 569,
    w: 212,
    h: 286,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_marketplace',
    name: 'Marketplace Stalls',
    url: '/maps/plaza/layers/marketplace.png',
    x: 300,
    y: 180,
    w: 326,
    h: 275,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_board',
    name: 'Bulletin Board',
    url: '/maps/plaza/layers/board.png',
    x: 1550,
    y: 250,
    w: 297,
    h: 188,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_bushes',
    name: 'Plaza Bushes',
    url: '/maps/plaza/layers/bushes.png',
    x: 1600,
    y: 320,
    w: 202,
    h: 139,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_rocky',
    name: 'Rocky Formation',
    url: '/maps/plaza/layers/rocky.png',
    x: 1750,
    y: 980,
    w: 178,
    h: 152,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_random_pole',
    name: 'Lamppost & Poles',
    url: '/maps/plaza/layers/random-pole.png',
    x: 700,
    y: 600,
    w: 369,
    h: 114,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
  {
    id: 'layer_object_7',
    name: 'Plaza Decor',
    url: '/maps/plaza/layers/object-7.png',
    x: 1750,
    y: 900,
    w: 196,
    h: 228,
    slot: 'object',
    zOffset: 0,
    opacity: 1,
    visible: true,
  },
];
