import { NPCData } from '@/types/game';

export const NPCS: NPCData[] = [
  // --- Plaza Map NPCs ---
  {
    id: 'mayor',
    name: 'Mayor Pixel',
    pre: '⭐',
    av: 1,
    avatarId: 'pipoya_headmaster_male_png',
    hue: 210,
    tag: '#d7e9ff',
    mapId: 'plaza',
    home: { x: 1100, y: 680 },
    r: 320,
    spd: 55,
    npc: true,
    lines: [
      "Welcome to the Plaza! 🎉",
      "Report bugs at the Help Desk — coins await! 💰",
      "Someone got a PERFECT score at the Schoolhouse. Show-off 😄",
      "Have you checked the Bulletin Board today?",
    ],
    bub: ["Vote for me again! ⭐", "Cozy is a policy."],
    mem: ["Members only — keep it kind in here 💛", "Verified students get the good gossip."],
  },
  {
    id: 'gnome',
    name: 'Gossip Gnome',
    pre: '🍄',
    av: 2,
    avatarId: 'pipoya_pien_png',
    hue: 90,
    tag: '#d0f4de',
    mapId: 'plaza',
    home: { x: 480, y: 380 },
    r: 350,
    spd: 48,
    npc: true,
    lines: [
      "Psst… the vendor is buying wood today 🪵",
      "I saw someone place a lawn gnome. Tasteful.",
      "Invite your friends — free coins 💌",
      "The pond carp are gossiping about you.",
    ],
    bub: ["premium gossip loading…", "i know things 👀"],
    mem: ["premium channel only 😌"],
  },
  {
    id: 'cat',
    name: 'Plaza Cat',
    pre: '🐾',
    av: 3,
    avatarId: 'pipoya_cat_01-1_png',
    hue: 0,
    tag: '#ffe5cc',
    mapId: 'plaza',
    home: { x: 1750, y: 550 },
    r: 300,
    spd: 72,
    npc: true,
    lines: ["meow 🐱", "*knocks a pebble off the stall*", "mrrp.", "purr… warm plaza today."],
    bub: ["meow.", "*plotting*"],
    mem: [],
  },
  {
    id: 'dog',
    name: 'Plaza Pup',
    pre: '🐶',
    av: 0,
    avatarId: 'pipoya_dog_01-1_png',
    hue: 0,
    tag: '#e2f0d9',
    mapId: 'plaza',
    home: { x: 1400, y: 1150 },
    r: 350,
    spd: 65,
    npc: true,
    lines: ["woof woof! 🐶", "*chases tail*", "*sniffs the grass*", "arf!"],
    bub: ["woof!", "*pant pant*", "ball?!"],
    mem: [],
  },
  {
    id: 'sam',
    name: 'TransferSam',
    pre: '',
    av: 0,
    avatarId: 'pipoya_female_01-1_png',
    hue: 300,
    tag: '#ffd6e0',
    mapId: 'plaza',
    home: { x: 450, y: 1100 },
    r: 350,
    spd: 60,
    npc: false,
    lines: ["hi everyone! 👋", "anyone up for a quiz race later? ⚔", "just sold 5 wood, feeling rich 💰"],
    bub: ["first day here — so cozy!", "the cat knocked over my gnome 😭", "study session at the schoolhouse at 7pm!"],
    board: [
      "first day here, this place is cozy!",
      "anyone up for a quiz race later? ⚔",
      "just sold 5 wood, feeling rich 💰",
      "the cat knocked over my gnome again 😭",
      "tip: perfect quiz scores drop exclusive hats 🎓",
    ],
    mem: ["study session at the schoolhouse at 7pm!", "who's grinding modules tonight?"],
  },

  // --- Classroom / School Map NPCs ---
  {
    id: 'prof_hoot',
    name: 'Prof. Hoot',
    pre: '🎓',
    av: 1,
    avatarId: 'pipoya_headmaster_male_png',
    hue: 210,
    tag: '#d7e9ff',
    mapId: 'classroom',
    home: { x: 420, y: 380 },
    r: 160,
    spd: 45,
    npc: true,
    lines: [
      "Quiet in the classroom! 🤫",
      "Ready for today's quiz?",
      "Study hard and earn exclusive hat rewards! 🎓",
      "Check out the study reviewers on the right!",
    ],
    bub: ["Class is in session! 📖", "No whispering during tests! 🤫", "Need help with a module?"],
    mem: ["Check the reviewer desks for exam hints! 💡"],
  },
  {
    id: 'student_chloe',
    name: 'Chloe',
    pre: '✏️',
    av: 0,
    avatarId: 'pipoya_female_01-1_png',
    hue: 160,
    tag: '#d0f4de',
    mapId: 'classroom',
    home: { x: 800, y: 550 },
    r: 200,
    spd: 55,
    npc: true,
    lines: [
      "I've been studying all morning! 📚",
      "Did you know perfect scores get golden stars? ✨",
      "The library bookshelf has great guides!",
    ],
    bub: ["A+ student grind 💯", "Taking notes... ✍️", "Quiz time soon! 🎓"],
    mem: ["Who wants to study together? 🤝"],
  },
  {
    id: 'student_oliver',
    name: 'Oliver',
    pre: '🎒',
    av: 0,
    avatarId: 'pipoya_male_01-1_png',
    hue: 40,
    tag: '#ffe5cc',
    mapId: 'classroom',
    home: { x: 1350, y: 480 },
    r: 220,
    spd: 50,
    npc: true,
    lines: [
      "The reviewer bookshelves have all the notes! 📖",
      "I'm practicing for the quiz race! 🏁",
      "Don't forget to review before taking the exam!",
    ],
    bub: ["Reading chapter 4... 📖", "So much to learn! 🧠", "Reviewer 2 is super helpful!"],
    mem: ["Reviewing past exams... 📝"],
  },
  {
    id: 'school_mascot',
    name: 'Hammy',
    pre: '🐹',
    av: 3,
    avatarId: 'pipoya_cat_01-1_png',
    hue: 30,
    tag: '#fff2c2',
    mapId: 'classroom',
    home: { x: 1100, y: 800 },
    r: 180,
    spd: 65,
    npc: true,
    lines: ["squeak squeak! 🐹", "*nibbles sunflower seed*", "*runs on wheel*"],
    bub: ["squeak! 🐹", "*munch munch*", "*twitch ears*"],
    mem: [],
  },
];
