import type { StructureTemplate } from '@/types/editor';

export const STRUCTURE_TEMPLATES: StructureTemplate[] = [
  // ---- Plants (Rectangles & Circles) ----
  {
    id: 'tree_oak',
    label: '🌳 Oak Tree',
    category: 'plants',
    shape: 'rect',
    w: 96,
    h: 96,
    color: '#22c55e',
    defaultCollision: { x: 24, y: 56, w: 48, h: 32 },
  },
  {
    id: 'tree_canopy',
    label: '🌳 Round Tree Canopy',
    category: 'plants',
    shape: 'circle',
    w: 96,
    h: 96,
    color: '#16a34a',
    defaultCollision: { x: 24, y: 24, w: 48, h: 48, shape: 'circle' },
  },
  {
    id: 'tree_pine',
    label: '🌲 Pine Tree',
    category: 'plants',
    shape: 'rect',
    w: 80,
    h: 112,
    color: '#15803d',
    defaultCollision: { x: 24, y: 72, w: 32, h: 32 },
  },
  {
    id: 'bush_small',
    label: '🌿 Round Bush',
    category: 'plants',
    shape: 'circle',
    w: 48,
    h: 48,
    color: '#4ade80',
    defaultCollision: { x: 4, y: 4, w: 40, h: 40, shape: 'circle' },
  },
  {
    id: 'rock_round',
    label: '🪨 Round Rock',
    category: 'plants',
    shape: 'circle',
    w: 64,
    h: 64,
    color: '#64748b',
    defaultCollision: { x: 8, y: 8, w: 48, h: 48, shape: 'circle' },
  },

  // ---- Props & Structures ----
  {
    id: 'house_stone',
    label: '🏠 Stone House',
    category: 'structures',
    shape: 'rect',
    w: 160,
    h: 128,
    color: '#0284c7',
    defaultCollision: { x: 10, y: 64, w: 140, h: 56 },
  },
  {
    id: 'house_wood',
    label: '🏡 Wooden House',
    category: 'structures',
    shape: 'rect',
    w: 160,
    h: 128,
    color: '#d97706',
    defaultCollision: { x: 10, y: 64, w: 140, h: 56 },
  },
  {
    id: 'tower_round',
    label: '🏰 Round Tower / Pillar',
    category: 'structures',
    shape: 'circle',
    w: 96,
    h: 96,
    color: '#475569',
    defaultCollision: { x: 12, y: 12, w: 72, h: 72, shape: 'circle' },
  },
  {
    id: 'bench_wood',
    label: '🪑 Bench',
    category: 'props',
    shape: 'rect',
    w: 64,
    h: 40,
    color: '#b45309',
    defaultCollision: { x: 4, y: 12, w: 56, h: 24 },
  },
  {
    id: 'lamp_post',
    label: '💡 Lamp Post',
    category: 'props',
    shape: 'circle',
    w: 32,
    h: 64,
    color: '#f59e0b',
    defaultCollision: { x: 8, y: 44, w: 16, h: 16, shape: 'circle' },
  },
  {
    id: 'fountain_pond',
    label: '⛲ Round Pond / Fountain',
    category: 'props',
    shape: 'circle',
    w: 112,
    h: 112,
    color: '#38bdf8',
    defaultCollision: { x: 8, y: 8, w: 96, h: 96, shape: 'circle' },
  },
  {
    id: 'market_stall',
    label: '🏪 Stall',
    category: 'props',
    shape: 'rect',
    w: 112,
    h: 80,
    color: '#ec4899',
    defaultCollision: { x: 6, y: 40, w: 100, h: 36 },
  },
  {
    id: 'fence_row',
    label: '🚧 Fence',
    category: 'props',
    shape: 'rect',
    w: 96,
    h: 32,
    color: '#78350f',
    defaultCollision: { x: 0, y: 8, w: 96, h: 20 },
  },
  {
    id: 'portal_circle',
    label: '🔮 Circle Teleport Portal',
    category: 'structures',
    shape: 'circle',
    w: 64,
    h: 64,
    color: '#a855f7',
    defaultCollision: { x: 8, y: 8, w: 48, h: 48, shape: 'circle' },
  },

  // ---- Spawns (Kept as requested) ----
  {
    id: 'player_start',
    label: '🚩 Player Spawn',
    category: 'spawns',
    w: 32,
    h: 32,
    crop: { sheet: '/assets/topdown/TX Player.png', x: 0, y: 0, w: 32, h: 32 },
  },
  {
    id: 'npc_spawn',
    label: '👤 NPC Spawn',
    category: 'spawns',
    w: 32,
    h: 32,
    crop: { sheet: '/assets/topdown/TX Player.png', x: 32, y: 0, w: 32, h: 32 },
  },

  // ---- Custom Shapes & Ground Hitboxes ----
  {
    id: 'custom_rect',
    label: '📦 Custom Rect Block',
    category: 'custom',
    shape: 'rect',
    w: 64,
    h: 64,
    color: '#6366f1',
    defaultCollision: { x: 0, y: 0, w: 64, h: 64 },
  },
  {
    id: 'custom_circle',
    label: '⭕ Custom Circle Zone',
    category: 'custom',
    shape: 'circle',
    w: 64,
    h: 64,
    color: '#ec4899',
    defaultCollision: { x: 0, y: 0, w: 64, h: 64, shape: 'circle' },
  },
  {
    id: 'ground_hitbox',
    label: '🧱 Invisible Wall',
    category: 'custom',
    shape: 'rect',
    w: 96,
    h: 32,
    color: '#ef4444',
    defaultCollision: { x: 0, y: 0, w: 96, h: 32 },
  },
];
