-- ============================================================
--   PAYMENT_RECEIPTS TABLE & RLS POLICIES
--   Run this script in your Supabase SQL Editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.payment_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  student_name TEXT NOT NULL,
  week_number INTEGER NOT NULL,
  receipt_url TEXT NOT NULL,
  payment_method TEXT NOT NULL DEFAULT 'GCash', -- 'GCash' | 'Maya'
  amount NUMERIC(10, 2) NOT NULL DEFAULT 50.00,
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending' | 'approved' | 'rejected'
  rejection_reason TEXT,
  reference_number TEXT,
  note TEXT,
  file_name TEXT,
  file_size BIGINT,
  mime_type TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  reviewed_at TIMESTAMPTZ,
  reviewed_by TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.payment_receipts ENABLE ROW LEVEL SECURITY;

-- 1. SELECT: Anyone can view receipt statuses
CREATE POLICY "payment_receipts: select policy"
  ON public.payment_receipts FOR SELECT
  TO anon, authenticated
  USING (true);

-- 2. INSERT: Anyone can submit proof of payment
CREATE POLICY "payment_receipts: insert policy"
  ON public.payment_receipts FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- 3. UPDATE: Only officers and moderators can update receipts (approve/reject)
CREATE POLICY "payment_receipts: update policy"
  ON public.payment_receipts FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  );

-- 4. DELETE: Only officers and moderators can delete receipts
CREATE POLICY "payment_receipts: delete policy"
  ON public.payment_receipts FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.officers WHERE email = auth.jwt() ->> 'email'
    )
    OR EXISTS (
      SELECT 1 FROM public.moderators WHERE email = auth.jwt() ->> 'email'
    )
  );
